# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '..\tabs.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMainWindow
from Frontend.new_Dash import Dashboard


class Ui_tabsPage(object):
    def setupUi(self, tabsPage):
        tabsPage.setObjectName("tabsPage")
        tabsPage.resize(1404, 884)
        tabsPage.setMaximumSize(QtCore.QSize(1404, 884))
        tabsPage.setStyleSheet("QMainWindow{\n"
"background-color: white;\n"
"border-bottom-width: 3px;\n"
"border-left-width:3px;\n"
"border-right-width: 3px;\n"
"border-style: outset; \n"
"border-color:white;\n"
"}")
        self.centralwidget = QtWidgets.QWidget(tabsPage)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.tabWidget.setFont(font)
        self.tabWidget.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.tabWidget.setStyleSheet("QTabWidget::tab-bar {\n"
"    alignment: center;\n"
"}\n"
"\n"
"QTabBar::tab {\n"
"    background-color: white;\n"
"    border: 2px solid #C4C4C3;\n"
"    border-top-left-radius: 6px;\n"
"    border-top-right-radius: 6px;\n"
"    border-bottom-left-radius: 0px;\n"
"    border-bottom-right-radius: 0px;\n"
"    min-width: 50ex;\n"
"    padding: 2px;\n"
"    margin-left: 6px;\n"
"    margin-right: 6px;\n"
"}\n"
"\n"
"QTabBar::tab:selected {\n"
"    border-color: red;\n"
"    border-bottom: 0px;\n"
"    border-bottom-left-radius: 0px;\n"
"    border-bottom-right-radius: 0px;\n"
"    border-width:4px;\n"
"}\n"
"\n"
"QTabBar::tab:!selected {\n"
"    margin-top: 2px;\n"
"    background-color: white;\n"
"    border-bottom:0px;\n"
"    border-color: black;\n"
"    border-bottom-left-radius: 0px;\n"
"    border-bottom-right-radius: 0px;\n"
"}\n"
"\n"
"QTabWidget:pane  {\n"
"    border: 2px solid black; /* Set the border color for the content area */\n"
"    border-top-left-radius: 6px;\n"
"    border-top-right-radius: 6px;\n"
"    border-bottom-left-radius: 0px;\n"
"    border-bottom-right-radius: 0px;\n"
"}\n"
"QTabWidget::tab-bar {\n"
"    alignment: center;\n"
"}\n"
"\n"
"QTabBar::tab {\n"
"    background-color: white;\n"
"    border: 2px solid #C4C4C3;\n"
"    border-top-left-radius: 6px;\n"
"    border-top-right-radius: 6px;\n"
"    border-bottom-left-radius: 0px;\n"
"    border-bottom-right-radius: 0px;\n"
"    min-width: 50ex;\n"
"    padding: 2px;\n"
"    margin-left: 6px;\n"
"    margin-right: 6px;\n"
"}\n"
"\n"
"QTabBar::tab:selected {\n"
"    border-color: red;\n"
"    border-bottom: 0px;\n"
"    border-bottom-left-radius: 0px;\n"
"    border-bottom-right-radius: 0px;\n"
"    border-width: 4px;\n"
"}\n"
"\n"
"QTabBar::tab:!selected {\n"
"    margin-top: 2px;\n"
"    background-color: white;\n"
"    border-bottom: 0px;\n"
"    border-color: black;\n"
"    border-bottom-left-radius: 0px;\n"
"    border-bottom-right-radius: 0px;\n"
"}\n"
"\n"
"QTabWidget:pane {\n"
"    border: 2px solid red; /* Set the border color for the outline of the QTabWidget */\n"
"    border-top-left-radius: 6px;\n"
"    border-top-right-radius: 6px;\n"
"    border-bottom-left-radius: 0px;\n"
"    border-bottom-right-radius: 0px;\n"
"}")
        self.tabWidget.setTabPosition(QtWidgets.QTabWidget.North)
        self.tabWidget.setObjectName("tabWidget")
        self.log = QtWidgets.QWidget()
        self.log.setObjectName("log")
        self.logTable = QtWidgets.QTableWidget(self.log)
        self.logTable.setGeometry(QtCore.QRect(20, 10, 1341, 731))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.logTable.sizePolicy().hasHeightForWidth())
        self.logTable.setSizePolicy(sizePolicy)
        self.logTable.setMinimumSize(QtCore.QSize(760, 0))
        self.logTable.setAutoFillBackground(False)
        self.logTable.setStyleSheet(" /* LOG PAGE */\n"
"QTableWidget{\n"
"border: 3px outset black;\n"
"}\n"
"QTableWidget:bar{\n"
"border: 3px outset black;\n"
"}\n"
"QHeaderView {\n"
"    border: 2px solid black;\n"
"    border-top-style:null;\n"
"    border-left-style:null;\n"
"    border-right-style:null;\n"
"}\n"
"QTableWidget::item {\n"
"    background-color: rgba(255,0,0,90);\n"
"    color: black;\n"
"}\n"
"")
        self.logTable.setAutoScroll(False)
        self.logTable.setAlternatingRowColors(True)
        self.logTable.setSelectionMode(QtWidgets.QAbstractItemView.ContiguousSelection)
        self.logTable.setShowGrid(True)
        self.logTable.setCornerButtonEnabled(False)
        self.logTable.setRowCount(0)
        self.logTable.setObjectName("logTable")
        self.logTable.setColumnCount(4)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.logTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.logTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.logTable.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.logTable.setHorizontalHeaderItem(3, item)
        self.logTable.horizontalHeader().setCascadingSectionResizes(False)
        self.logTable.horizontalHeader().setDefaultSectionSize(339)
        self.logTable.horizontalHeader().setHighlightSections(True)
        self.logTable.horizontalHeader().setSortIndicatorShown(False)
        self.logTable.verticalHeader().setVisible(False)
        self.logTable.verticalHeader().setCascadingSectionResizes(False)
        self.logTable.verticalHeader().setHighlightSections(True)
        self.logTable.verticalHeader().setSortIndicatorShown(False)
        self.logTable.verticalHeader().setStretchLastSection(False)
        self.dashboardButton_logs = QtWidgets.QPushButton(self.log)
        self.dashboardButton_logs.setGeometry(QtCore.QRect(1190, 750, 151, 51))
        self.dashboardButton_logs.setStyleSheet("QPushButton{\n"
"border: 2px outset black;\n"
"background:red;\n"
"color: white;\n"
"font: bold 14pt;\n"
"border-radius: 20px;\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"border: 2px outset black;\n"
"background:white;\n"
"color: black;\n"
"font: bold 14pt;\n"
"}")
        self.dashboardButton_logs.setObjectName("dashboardButton_logs")
        self.tabWidget.addTab(self.log, "")
        self.alerts = QtWidgets.QWidget()
        self.alerts.setObjectName("alerts")
        self.dashboardButton_alerts = QtWidgets.QPushButton(self.alerts)
        self.dashboardButton_alerts.setGeometry(QtCore.QRect(1190, 750, 151, 51))
        self.dashboardButton_alerts.setStyleSheet("QPushButton{\n"
"border: 2px outset black;\n"
"background:red;\n"
"color: white;\n"
"font: bold 14pt;\n"
"border-radius: 20px;\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"border: 2px outset black;\n"
"background:white;\n"
"color: black;\n"
"font: bold 14pt;\n"
"}")
        self.dashboardButton_alerts.setObjectName("dashboardButton_alerts")
        self.activeAlertsTable = QtWidgets.QTableWidget(self.alerts)
        self.activeAlertsTable.setGeometry(QtCore.QRect(20, 80, 1341, 171))
        self.activeAlertsTable.setStyleSheet(" /* ALERTS PAGE */\n"
"QTableWidget{\n"
"border: 3px outset black;\n"
"}\n"
"QTableWidget:bar{\n"
"border: 3px outset black;\n"
"}\n"
"QHeaderView {\n"
"    border: 2px solid black; /* Adjust the thickness and color as needed */\n"
"    border-top-style:null;\n"
"    border-left-style:null;\n"
"    border-right-style:null;\n"
"}\n"
"QTableWidget::item {\n"
"    background-color: rgba(255,0,0,90);\n"
"    color: black;\n"
"}\n"
"")
        self.activeAlertsTable.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.activeAlertsTable.setAutoScroll(False)
        self.activeAlertsTable.setAlternatingRowColors(True)
        self.activeAlertsTable.setCornerButtonEnabled(False)
        self.activeAlertsTable.setRowCount(0)
        self.activeAlertsTable.setObjectName("activeAlertsTable")
        self.activeAlertsTable.setColumnCount(5)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.activeAlertsTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.activeAlertsTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.activeAlertsTable.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.activeAlertsTable.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.activeAlertsTable.setHorizontalHeaderItem(4, item)
        self.activeAlertsTable.horizontalHeader().setDefaultSectionSize(267)
        self.activeAlertsTable.verticalHeader().setVisible(False)
        self.label = QtWidgets.QLabel(self.alerts)
        self.label.setGeometry(QtCore.QRect(520, 50, 351, 21))
        font = QtGui.QFont()
        font.setPointSize(19)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.pastAlertsTable = QtWidgets.QTableWidget(self.alerts)
        self.pastAlertsTable.setGeometry(QtCore.QRect(20, 350, 1341, 371))
        self.pastAlertsTable.setStyleSheet("QTableWidget{\n"
"border: 3px outset black;\n"
"}\n"
"QTableWidget:bar{\n"
"border: 3px outset black;\n"
"}\n"
"QHeaderView {\n"
"    border: 2px solid black; /* Adjust the thickness and color as needed */\n"
"    border-top-style:null;\n"
"    border-left-style:null;\n"
"    border-right-style:null;\n"
"}\n"
"QTableWidget::item {\n"
"    color: black;\n"
"    text-align: center;\n"
"    background: rgba(128,128,128,60);\n"
"}\n"
"")
        self.pastAlertsTable.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.pastAlertsTable.setAutoScroll(False)
        self.pastAlertsTable.setAlternatingRowColors(True)
        self.pastAlertsTable.setCornerButtonEnabled(False)
        self.pastAlertsTable.setRowCount(0)
        self.pastAlertsTable.setObjectName("pastAlertsTable")
        self.pastAlertsTable.setColumnCount(5)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.pastAlertsTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.pastAlertsTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.pastAlertsTable.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.pastAlertsTable.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.pastAlertsTable.setHorizontalHeaderItem(4, item)
        self.pastAlertsTable.horizontalHeader().setDefaultSectionSize(267)
        self.pastAlertsTable.verticalHeader().setVisible(False)
        self.label_2 = QtWidgets.QLabel(self.alerts)
        self.label_2.setGeometry(QtCore.QRect(520, 300, 351, 21))
        font = QtGui.QFont()
        font.setPointSize(19)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.tabWidget.addTab(self.alerts, "")
        self.action = QtWidgets.QWidget()
        self.action.setObjectName("action")
        self.dashboardButton_actions = QtWidgets.QPushButton(self.action)
        self.dashboardButton_actions.setGeometry(QtCore.QRect(1190, 750, 151, 51))
        self.dashboardButton_actions.setStyleSheet("QPushButton{\n"
"border: 2px outset black;\n"
"background:red;\n"
"color: white;\n"
"font: bold 14pt;\n"
"border-radius: 20px;\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"border: 2px outset black;\n"
"background:white;\n"
"color: black;\n"
"font: bold 14pt;\n"
"}")
        self.dashboardButton_actions.setObjectName("dashboardButton_actions")
        self.columnView = QtWidgets.QColumnView(self.action)
        self.columnView.setGeometry(QtCore.QRect(10, 110, 1361, 511))
        self.columnView.setStyleSheet(" /* ACTIONS PAGE */")
        self.columnView.setObjectName("columnView")
        self.tabWidget.addTab(self.action, "")
        self.settings = QtWidgets.QWidget()
        self.settings.setObjectName("settings")
        self.dashboardButton_settings = QtWidgets.QPushButton(self.settings)
        self.dashboardButton_settings.setGeometry(QtCore.QRect(1190, 750, 151, 51))
        self.dashboardButton_settings.setStyleSheet("QPushButton{\n"
"border: 2px outset black;\n"
"background:red;\n"
"color: white;\n"
"font: bold 14pt;\n"
"border-radius: 20px;\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"border: 2px outset black;\n"
"background:white;\n"
"color: black;\n"
"font: bold 14pt;\n"
"}")
        self.dashboardButton_settings.setObjectName("dashboardButton_settings")
        self.tabWidget.addTab(self.settings, "")
        self.gridLayout.addWidget(self.tabWidget, 0, 0, 1, 1)
        tabsPage.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(tabsPage)
        self.statusbar.setObjectName("statusbar")
        tabsPage.setStatusBar(self.statusbar)

        self.retranslateUi(tabsPage)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(tabsPage)

    def retranslateUi(self, tabsPage):
        _translate = QtCore.QCoreApplication.translate
        tabsPage.setWindowTitle(_translate("tabsPage", "MainWindow"))
        item = self.logTable.horizontalHeaderItem(0)
        item.setText(_translate("tabsPage", "Date"))
        item = self.logTable.horizontalHeaderItem(1)
        item.setText(_translate("tabsPage", "Time"))
        item = self.logTable.horizontalHeaderItem(2)
        item.setText(_translate("tabsPage", "Packet"))
        item = self.logTable.horizontalHeaderItem(3)
        item.setText(_translate("tabsPage", "Details"))
        self.dashboardButton_logs.setText(_translate("tabsPage", "Dashboard"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.log), _translate("tabsPage", "Logs"))
        self.dashboardButton_alerts.setText(_translate("tabsPage", "Dashboard"))
        item = self.activeAlertsTable.horizontalHeaderItem(0)
        item.setText(_translate("tabsPage", "Date"))
        item = self.activeAlertsTable.horizontalHeaderItem(1)
        item.setText(_translate("tabsPage", "Destination IP"))
        item = self.activeAlertsTable.horizontalHeaderItem(2)
        item.setText(_translate("tabsPage", "Source IP"))
        item = self.activeAlertsTable.horizontalHeaderItem(3)
        item.setText(_translate("tabsPage", "Destination Port"))
        item = self.activeAlertsTable.horizontalHeaderItem(4)
        item.setText(_translate("tabsPage", "Source Port"))
        self.label.setText(_translate("tabsPage", "Active Alerts"))
        item = self.pastAlertsTable.horizontalHeaderItem(0)
        item.setText(_translate("tabsPage", "Date"))
        item = self.pastAlertsTable.horizontalHeaderItem(1)
        item.setText(_translate("tabsPage", "Destination IP"))
        item = self.pastAlertsTable.horizontalHeaderItem(2)
        item.setText(_translate("tabsPage", "Source IP"))
        item = self.pastAlertsTable.horizontalHeaderItem(3)
        item.setText(_translate("tabsPage", "Destination Port"))
        item = self.pastAlertsTable.horizontalHeaderItem(4)
        item.setText(_translate("tabsPage", "Source Port"))
        self.label_2.setText(_translate("tabsPage", "Past Alerts"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.alerts), _translate("tabsPage", "Alerts"))
        self.dashboardButton_actions.setText(_translate("tabsPage", "Dashboard"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.action), _translate("tabsPage", "Actions"))
        self.dashboardButton_settings.setText(_translate("tabsPage", "Dashboard"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.settings), _translate("tabsPage", "Settings"))
        self.dashboardButton_logs.clicked.connect(lambda: self.showDashboard(tabsPage))
        self.dashboardButton_alerts.clicked.connect(lambda: self.showDashboard(tabsPage))
        self.dashboardButton_actions.clicked.connect(lambda: self.showDashboard(tabsPage))
        self.dashboardButton_settings.clicked.connect(lambda: self.showDashboard(tabsPage))

    def showDashboard(self, tabsPage):
        dashboard_Widget = Dashboard()
        tabsPage.setCentralWidget(dashboard_Widget)

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    tabsPage = QtWidgets.QMainWindow()
    ui = Ui_tabsPage()
    ui.setupUi(tabsPage)
    tabsPage.show()
    sys.exit(app.exec_())
