# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'wizard.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Wiz(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(400, 247)
        Form.setStyleSheet("")
        self.gridLayout_2 = QtWidgets.QGridLayout(Form)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.frame = QtWidgets.QFrame(Form)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout = QtWidgets.QGridLayout(self.frame)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setStyleSheet("background-color: transparent;")
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 2, alignment=QtCore.Qt.AlignCenter)

        self.listWidget = QtWidgets.QListWidget(self.frame)
        self.listWidget.setObjectName("listWidget")
        self.gridLayout.addWidget(self.listWidget, 1, 0, 4, 1)

        self.frame_2 = QtWidgets.QFrame(self.frame)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.gridLayout_2.addWidget(self.frame, 0, 0, 1, 1)

        self.gridLayout_2.addWidget(self.frame, 0, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.frame_2)
        self.label_3.setGeometry(QtCore.QRect(10, 0, 191, 16))
        self.label_3.setStyleSheet("background-color: transparent;")
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.frame_2, 4, 1, 1, 1)

        self.textEdit = QtWidgets.QTextEdit(self.frame_2)
        self.textEdit.setGeometry(QtCore.QRect(50, 20, 131, 51))
        self.textEdit.setReadOnly(True)
        self.textEdit.setObjectName("textEdit")

        self.checkBox = QtWidgets.QCheckBox(self.frame_2)
        self.checkBox.setGeometry(QtCore.QRect(10, 40, 44, 12))
        self.checkBox.setObjectName("checkBox")

        self.pushButton = QtWidgets.QPushButton(self.frame_2)
        self.pushButton.setGeometry(QtCore.QRect(120, 80, 56, 17))
        self.pushButton.setObjectName("pushButton")

        self.label_4 = QtWidgets.QLabel(self.frame)
        self.label_4.setStyleSheet("background-color: transparent;")
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 1, 1, 1, 1, alignment=QtCore.Qt.AlignTop)

        self.spinBox = QtWidgets.QSpinBox(self.frame)
        self.spinBox.setObjectName("spinBox")
        self.gridLayout.addWidget(self.spinBox, 2, 1, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_3.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:9pt; font-weight:600;\">Would you like to receive notifications?</span></p></body></html>"))
        self.textEdit.setHtml(_translate("Form", "<html><head/><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:5.5pt; font-weight:400; font-style:normal;\">\n"
"<p>If checked you will receive notifications</p>\n"
"<p>If <span style=\" font-style:italic;\">Unchecked</span> you will NOT receive notifications.</p>\n"
"<p>This can be changed in the settings.</p></body></html>"))
        self.checkBox.setText(_translate("Form", "Yes"))
        self.pushButton.setText(_translate("Form", "Finish"))
        self.label.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt; color:#0000ff;\">Welcome To </span><span style=\" font-size:14pt; font-weight:600; text-decoration: underline; color:#0000ff;\">IntruWatch</span></p></body></html>"))
        self.label_4.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:9pt; font-weight:600;\">Please Select an Interface from the Left.</span></p></body></html>"))


